[package]
name = "mogan"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
mogan-core = { path = "../crates/mogan-core" }
mogan-typst = { path = "../crates/mogan-typst" }
mogan-convert = { path = "../crates/mogan-convert" }
mogan-bib = { path = "../crates/mogan-bib" }
mogan-math = { path = "../crates/mogan-math" }
mogan-ai = { path = "../crates/mogan-ai" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
log.workspace = true
env_logger.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[lib]
name = "mogan_lib"
crate-type = ["lib", "cdylib", "staticlib"]
